genesiscommunitysuccess/blank-app-seed

- .github/pull_request_templae.md
-added PR template for blank app seed
https://genesisglobal.atlassian.net/browse/PTC-468
> chore: add pull request template PTC-468

- .github/pull_request_templae.md
- add PR template to master
https://genesisglobal.atlassian.net/browse/PTC-468
-tested that the pr template doesn't end up in the genertaed seed
> chore: add pull request template PTC-468 (#6)

- .github/CODEOWNERS
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- server/jvm/build.gradle.kts
- server/jvm/genesis-deploy/build.gradle.kts
- server/jvm/gradle/wrapper/gradle-wrapper.properties
[Review Guidance](https://genesisglobal.atlassian.net/wiki/spaces/ON/pages/2682257431/Platform+Code+Review+Process)
[PTC-544](https://genesisglobal.atlassian.net/browse/PTC-544)
> chore: upgrade server versions, add Nenko to CODEOWNERS PTC-544

- client/web/package.json
[Review Guidance](https://genesisglobal.atlassian.net/wiki/spaces/ON/pages/2682257431/Platform+Code+Review+Process)
https://genesisglobal.atlassian.net/browse/PTC-570
Add dependancy which is required for following the tutorials
> chore(blank-app-seed): Add foundation-ui dependancy PTC-407

- server/jvm/Dockerfile
[PA-324](https://genesisglobal.atlassian.net/browse/PA-324)
- Calls dos2unix for any .sh file to make sure that script is in unix (lf line ending) format 
> fix: make sure line endings are in unix format in .sh file PA-324

- client/web/package.json
- client/web/src/components/components.ts
Add the g2plot-chart package and register it in components.ts
> build: update dependency of foundation-ui

- server/jvm/build.gradle.kts
[PTC-809](https://genesisglobal.atlassian.net/browse/PTC-809)
- fixes duplicate error that occasionally appears in Intellij
> fix: stop duplicate error appearing in project: PTC-809

- server/jvm/gradle.properties
> chore: release to 6.4.0

- .genx/configure.js
- .genx/package.json
https://genesisglobal.atlassian.net/browse/PTC-420
> fix: overwrites files based on configuration PTC-420

- client/web/src/layouts/default.ts
- client/web/src/main/main.template.ts
[FUI-898](https://genesisglobal.atlassian.net/browse/FUI-898)
- Fix for luminance toggle button
> fix: add functionality to luminance toggle button FUI-898

- .genx/answers.js
- .genx/package.json
- .genx/prompts/ds.js
- .genx/prompts/messages.js
- .genx/prompts/package.js
[FUI-1100](https://genesisglobal.atlassian.net/browse/FUI-1100)
- Bumps dependency version which allows to use this without JFrog `.npmrc` config
* `mv ~/.npmrc ~/.npmrc-backup`
* Install using the **test** seed: `App seed Quick Start Application - Test`
* `mv ~/.npmrc-backup ~/.npmrc`
> chore: bumping foundation utils version FUI-1100

- client/package.json
- client/web/package.json
[DVOP-392](https://genesisglobal.atlassian.net/browse/DVOP-392)
- Adds an extra npm script config for the intellij plugin so that it can override the API_HOST
> chore: adds npm scripts that allow the use of the API_HOST override

- client/.build/webpack/config/devServers.js
- client/.build/webpack/config/webpack.common.js
- client/web/webpack.config.js
- Add dev server proxy configuration to allow local development using remote server
> chore: add dev server proxy config

- .genx/prompts/api.js
- .genx/prompts/ds.js
- .genx/prompts/package.js
https://genesisglobal.atlassian.net/browse/FUI-1383
- As titled
Prompt files
* Test for regressions using local checkout
> chore: allowing to supply answers via CLI FUI-1383

- .genx/prompts/api.js
https://genesisglobal.atlassian.net/browse/FUI-1383
- As titled
Prompts file
No impact with current CLI
> chore: allow to specify SSO config via CLI FUI-1383

- client/web/build.gradle.kts
https://genesisglobal.atlassian.net/browse/GSF-5885
> chore: removed duplicate code

- server/jvm/build.gradle.kts
[PTL-812](https://genesisglobal.atlassian.net/browse/PTL-812)
This task is regarding removing the task copyUserNpmrc as it is no longer needed since UI packages are all available from public NPM registry without a special .npmrc
> PTL-812 Remove copyUserNpmrc task

- .github/workflows/build.yml
- .github/workflows/upgrade.yml
FUI-1321
- Adds workflow files
> chore: initial Github workflow setup FUI-1321

- .gitignore
- server/jvm/gradle.properties
https://genesisglobal.atlassian.net/browse/PSD-2
- As titled
```
npx -y @genesislcap/genx@latest init prtest -x --ref 0b6639af7de72076d1ffcd03b9e45562fd792273
```
> chore: updated gradle.properties file and .gitignore PSD-2

- .github/workflows/upgrade.yml
[PSD-1](https://genesisglobal.atlassian.net/browse/PSD-1)
Find latest release version of framework packages(server side)
```
```
> PSD-1 Find latest release version of framework packages(server side) for blank-app-seed build

- .github/workflows/upgrade.yml
https://genesisglobal.atlassian.net/browse/PSD-9
Fix for
```
1 file changed, 4 insertions(+), 4 deletions(-)
fatal: The current branch chore-dep-update has no upstream branch.
To push the current branch and set the remote as upstream, use
git push --set-upstream origin chore-dep-update
To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
```
https://github.com/genesiscommunitysuccess/blank-app-seed/actions/runs/5880792443/job/15947858804
📑 &nbsp; **How should this be …
> chore: updated auth details and execution env PSD-9 PSD-9

- .genx/.releaserc
- .genx/package-lock.json
- .genx/package.json
- .github/workflows/build.yml
- .github/workflows/pr-title-check.yml
https://genesisglobal.atlassian.net/browse/PSD-8
- Adds semantic-release config and PR title validation
.releaserc
No real way to test until merged. Using the same config as in other repos where it works.
> chore: automated releases PSD-8

- .genx/.releaserc
- .github/workflows/release.yml
- CHANGELOG.md
https://genesisglobal.atlassian.net/browse/PSD-8
- Updates Git pattern to include changelog
- Adds releases notes from v1.0.0 to changelog
.releaserc
Will be tested during next release
> chore: fix changelog path in release Git config PSD-8

- .genx/details.js
- .genx/package.json
part 2 of https://github.com/genesislcap/foundation-ui/pull/1087
> feat: allow file exclusions when generating app from seeds PSD-5

- gradle.properties
- server/jvm/gradle.properties
- server/jvm/settings.gradle.kts
- settings.gradle.kts
[PSD-20](https://genesisglobal.atlassian.net/browse/PSD-20)
This task is about enabling the local build cache and configure it to store the caches in parent project directory
```
```
> feat: Enable local gradle build cache PSD-20

- .genx/details.js
PSD-31
Improves the next steps message to include a `cd client` step.
```
genx init test -s blank-app-seed --remote --ref PSD-31 -x
```
> chore: improve next steps message (add cd client) PSD-31

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade.yml
- client/Dockerfile
- client/build.gradle.kts
https://genesisglobal.atlassian.net/browse/FUI-1471
- Bumps Node to v20 which becomes LTS on 24 Oct https://nodejs.dev/en/about/releases/
Anywhere
```
```
> chore: bumping to Node 20 FUI-1471

- .github/workflows/build.yml
[PSD-36](https://genesisglobal.atlassian.net/browse/PSD-36)
**setup-java** action changes:
- Updated Java version to support version 7 of framework
- Changed the Java distribution from adopt to temurin to keep it similar to framework and also as per suggestion on setup-java action documentation [here](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#adopt)
-  Utilize built-in functionality to cache gradle dependencies
```
npx -y @genesislcap/genx@latest init prtest -x --ref …
```
> chore: Update Java version for V7 of framework PSD-36

- .github/workflows/slack.yml
https://genesisglobal.atlassian.net/browse/PSD-38
- Posts slack message when a new PR is raised
> chore: Slack notification for new PRs PSD-38

- .genx/scripts/update-versions.js
[PSD-42](https://genesisglobal.atlassian.net/browse/PSD-42)
Contains temporary fix to ignore test artifacts while getting latest version of the framework. Better solution on this to ignore any non-standard artifacts will be added as part of this ticket[ PSD-43](https://genesisglobal.atlassian.net/browse/PSD-43)
```
```
> chore: Improve Jfrog cli command to get latest version to exclude test artifacts(PSD-42)

- .genx/tests/fixtures/testapp/client/src/routes/home/home.template.ts
- .github/workflows/build.yml
- client/package.json
- client/src/components/components.ts
- client/src/layouts/default.ts
- client/src/main/main.ts
- client/src/routes/config.ts
- client/src/routes/home/home.styles.ts
- client/src/routes/home/home.ts
- client/src/routes/not-found/not-found.ts
- client/src/utils/logger.ts
[FUI-1735](https://genesisglobal.atlassian.net/jira/software/c/projects/FUI/issues/FUI-1735)
- Add lint/stylelint/prettier config packages to blank-app-seed
client/package.json
```
npx -y @genesislcap/genx@latest init prtest -x --ref sz/FUI-1735
```
> fix: add lint/stylelint/prettier config packages FUI-1735

- .releaserc
PSD-45
- Package lock contains package version, which is bumped during release, so it needs to be included in release commit too
.releaserc
No particular way of testing until the next release
> chore: include updated package lockfile in a release commit PSD-45

- .genx/package.json
- server/{{appName}}-app/src/main/genesis/cfg/{{appName}}-processes.xml
- server/{{appName}}-app/src/main/genesis/cfg/{{appName}}-service-definitions.xml
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-consolidator.kts
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-data-pipeline.kts
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-dataserver.kts
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-eventhandler.kts
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-streamer-client.kts
- server/{{appName}}-app/src/main/genesis/scripts/{{appName}}-streamer.kts
[PLAT-1067](https://genesisglobal.atlassian.net/browse/PLAT-1067)
```
```
> feat: Add default scripts and config files to seed (PLAT-1067)

- client/package.json
[FUI-1827](https://genesisglobal.atlassian.net/browse/FUI-1827)
- Bump LSP versions
> chore: bump lsp versions FUI-1827

- README.md
> chore: fix README link to server README (DVOP-619)

- .genx/package.json
- server/{{appName}}-app/src/main/genesis/cfg/{{appName}}-processes.xml
- Fix consolidator placeholder process to be GPAL
- Interpolate variables in XML files so app name added to process and service definitions xml files
```
```
> fix: consolidator as gpal and interpolate variables in xml files DVOP-620

- .gitignore
- server/build.gradle.kts
- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
[PSD-50](https://genesisglobal.atlassian.net/browse/PSD-50)
Make H2 the default DB in blank app seed
```
```
> feat: Make H2 the default DB in blank app seed(PSD-50)

- client/.editorconfig
- client/package.json
- client/src/components/components.ts
- client/src/layouts/default.ts
- client/src/main/main.css
- client/src/main/main.styles.ts
- client/src/main/main.template.ts
- client/src/main/main.ts
- client/src/pbc/README.md
- client/src/routes/config.ts
- client/src/store/index.ts
- client/src/store/store.ts
- client/src/typings.d.ts
PLAT-1028
- Enables integration with genesis PBCs
```
npx -y @genesislcap/genx@latest init prtest -x --ref ms/pbc-integration --no-shell && \
cd prtest && \
git init && git add --all && git commit -m 'init' && cd .. && \
npx -y @genesislcap/genx@latest add prtest -s pbc-reporting-seed && \
git status
```
```
npx -y @genesislcap/genx@latest init prtest2 -x --ref ms/pbc-integration --no-shell && \
cd prtest2 && \
git init && git add --all && git commit -m 'init' && cd .. && \
npx -y …
```
> feat: add ui pbc compatibility PLAT-1028

- server/gradle.properties
[PBC-101](https://genesisglobal.atlassian.net/browse/PBC-101)
- add version to gradle.properties.
```
```
> fix: add version to gradle.properties. (PBC-101)

- .genx/configure.js
- .genx/details.js
- .github/workflows/build.yml
https://genesisglobal.atlassian.net/browse/PA-1156
- Allows using uppercase characters in app name
- Updates next steps instructions to include creating Git repo (which also removes the Git error by Webpack dashboard plugin)
```
fatal: not a git repository (or any of the parent directories): .git
Error: Command failed: git rev-parse HEAD
```
```
npx -y @genesislcap/genx@latest init MyApp -x --ref ac/PA-1156
```
> fix: handling uppercase characters in app name PA-1156

- .genx/configure.js
- .genx/prompts/ui.js
- .genx/templates/chart.hbs
- .genx/templates/entityManager.hbs
- .genx/templates/form.hbs
- .genx/templates/grid.hbs
- .genx/templates/route.hbs
- .genx/templates/route.styles.hbs
- .genx/templates/route.template.hbs
- client/src/routes/config.ts
[GENC-68](https://genesisglobal.atlassian.net/browse/GENC-68)
- routes and components generation using templates
Providing config with prompts:
```
npx -y @genesislcap/genx@latest init prtest -x --ref ms/GENC-68-generating-components --apiHost 'wss://public-foundation.genesislab.global/gwf/'
```
Providing config with parameter:
```
npx -y @genesislcap/genx@latest init prtest -x --ref ms/GENC-68-generating-components --routes '[{"name":"home","tiles":[{"title":"Entity manager …
```
> feat: routes and components generation GENC-68 

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
```
npx -y @genesislcap/genx@latest init prtest -x --ref YOUR-BRANCH-NAME --no-npm
```
> fix: add SqlEnableSequenceGeneration as true GENC-197

- .github/workflows/upgrade.yml
https://genesisglobal.atlassian.net/browse/GENC-201
- Looks like there was a breaking change in octokit-core v6. Pinning at v5.
upgrade workflow file
Tricky to test because only main branch has the full env access.
> chore: locking octokit version GENC-201

- README.md
https://genesisglobal.atlassian.net/browse/GENC-122
- As titled
Readme
> fix: note about loading as Gradle project GENC-122

- server/{{appName}}-app/build.gradle.kts
```
npx -y @genesislcap/genx@latest init prtest -x --ref YOUR-BRANCH-NAME --no-npm
```
> chore: Remove copyDependencies from main module

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
[GENC-196](https://genesisglobal.atlassian.net/browse/GENC-196)
```
npx -y @genesislcap/genx@latest init prtest -x --ref YOUR-BRANCH-NAME --no-npm
```
> chore: replace env system definitions with item definitions. (GENC-196)

- .genx/templates/route.template.hbs
[GENC-259](https://genesisglobal.atlassian.net/browse/GENC-259)
- Support lowercase characters and spaces in route generation
- .genx/templates/route.template.hbs
```
npx -y @genesislcap/genx@latest init prtest -x --ref sz/GENC-259 --no-npm --routes '[{"name":"Abc Xyz","tiles":[{"title":"Entity manager tile","type":"entity-manager","config":{"resourceName":"ALL_COUNTERPARTYS","title":"Counterparty Management","updateEvent":"EVENT_COUNTERPARTY_MODIFY","deleteEvent":"EVENT_COUNTERPARTY_DELETE","createEvent":"EVENT_COUNTERPARTY_INSER …
```
> fix: support lowercase characters and spaces in route generation GENC-259

- .genx/configure.js
- .genx/prompts.js
- .genx/prompts/server.js
- .genx/prompts/ui.js
- .genx/templates/entityManager.hbs
- .genx/templates/grid.hbs
- .genx/templates/route.template.hbs
- .genx/utils.js
- client/package.json
- client/src/main/main.ts
- client/src/utils/fdc3.ts
- client/src/utils/index.ts
GENC-224
- Adds support for subscribing to FDC3 channels on ready
- Adds support for sending FDC3 messages on grid events
Out of scope for this PR:
* template formatting
* using utils from `@genesislcap/foundation-fdc3`
Templates
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/GENC-224-v2 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{"resourceName":"ALL_POSITIONS","title":"My …
```
> feat: FDC3 support GENC-224

- .genx/templates/gridLayout.hbs
- .genx/templates/horizontalLayout.hbs
- .genx/templates/route.template.hbs
- .genx/templates/tabsLayout.hbs
- .genx/utils.js
[GENC-286](https://genesisglobal.atlassian.net/browse/GENC-286)
Add new layout types (layoutType on route config)
- GridLayout
- TabsLayout
- HorizontalLayout
In genesis create, depending on the number of tiles, a different layout will be set
Less than 4 - horizontalLayout
4 - gridLayout
More than 4 - tabsLayout
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-286 --routes '[{"name":"TabsLayout", "layoutType": "tabs-layout", …
```
> feat: new layout types GENC-286

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
> feat: Add parent folder for h2 database GENC-289

- .genx/templates/route.template.hbs
- .genx/utils.js
- client/package.json
- client/src/utils/formatters.ts
- client/src/utils/index.ts
[GENC-265](https://genesisglobal.atlassian.net/browse/GENC-265)
- `getNumberFormatter` function implementation (under the hood used numeral.js)
-  Serialize columnDefs and columns to correctly pass the valueFormatter function with routes parameter
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-265 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-265 --no-npm -x --routes …
```
> feat: add support for number formatting GENC-265

- client/package.json
[GENC-372](https://genesisglobal.atlassian.net/browse/GENC-372)
- add webpack to plugin ui command.
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> fix: add webpack to plugin ui command. (GENC-372)

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
[GSF-6789](https://genesisglobal.atlassian.net/browse/GSF-6789)
- Adds new system definition property to avoid having to run the "SetPrimary" command using the Intellij Plugin to mark the local cluster environment as the primary node. This change reduces friction when running a genesis environment locally as processes marked as "primaryOnly" can only run if the cluster node has been marked as primary and otherwise stay in "STAND_BY".
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest …
```
> feat: Add PrimaryIfSingleNode system definition setting to automatically set a cluster node as primary if no other hosts are defined (GSF-6789)

- client/src/layouts/default.ts
[GENC-371](https://genesisglobal.atlassian.net/browse/GENC-371)
- As titled
```
```
``` …
```
> fix: remove side-bar menu contents GENC-371

- client/src/routes/config.ts
[AUTH-422](https://genesisglobal.atlassian.net/browse/AUTH-422)
- Login routes (reset password, forgot password, etc.) to work correctly.
`client\src\routes\config.ts`
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", …
```
> fix: add hostPath to login configuration (AUTH-422)

- .genx/templates/entityManager.hbs
- .genx/templates/grid.hbs
> feat: handle reqrep datasource types for grid and em GENC-436

- .github/workflows/upgrade.yml
PSD-9
- Ensures that FUI/GSF version update publishes a new version of the seed (chore doesn't trigger a new version in semver)
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> chore: making fix the default dependency upgrade commit type PSD-9

- client/src/utils/formatters.ts
GENC-496
- As titled
Formatter utils
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/GENC-496 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref Yac/GENC-496 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> fix: bigdecimal number formatting GENC-496

- client/src/utils/formatters.ts
Fixing linting error in GENC-496 PR
```
```
``` …
```
> chore: lint fix GENC-496

- client/src/utils/fdc3.ts
https://genesisglobal.atlassian.net/browse/GENC-500
Recursively checks object being sent on the channel and strips out bigints.
client/src/utils/fdc3.ts
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> fix: Using stripping out bigints - GENC-500

- .github/workflows/release.yml
- .releaserc
GENC-511
- Support for pre-leases
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> chore: pre-release support GENC-511

- client/README.md
GENC-511
- Prerelease test
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> fix: remove reference to FAST GENC-511

- .github/workflows/build.yml
- .github/workflows/release.yml
- .releaserc
GENC-511
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> fix: build config update GENC-511

- .github/workflows/release.yml
- .releaserc
- package-lock.json
- package.json
GENC-511
- Use correct dist tag for prelreleases
```
```
``` …
```
> fix: populate dist tag correctly GENC-511

- server/{{appName}}-app/src/main/genesis/data/USER_ATTRIBUTES.csv
Without this editing user fails
```
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref YOUR-BRANCH-NAME --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> fix: Add USER_ATTRIBUTES record for admin user (GENC-0)

- client/src/utils/fdc3.ts
Fix linting error introduced in https://github.com/genesiscommunitysuccess/blank-app-seed/pull/239
> fix: fdc3 file to unix file endings and fix linting error GENC-292

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade.yml
Addressed the following warning:
Have a look at the updated .yml files, they have the same changes. All moving from V3 to V4.
Check the CI jobs when building this branch.
> chore: update CI actions from V3 to V4

- .github/workflows/build.yml
- .github/workflows/upgrade.yml
- As titled. Concurrency change isn't required for this strictly, just cuts down on the number of builds we need to do.
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/PTC-0 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/PTC-0 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ …
```
> chore: switching to JFrog API key instead of password PTC-0

- .genx/configure.js
- .genx/templates/csv.hbs
- .genx/utils.js
[GENC-473](https://genesisglobal.atlassian.net/browse/GENC-473)
- ability to add/append data to csv files
- .genx/utils.js
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-473 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-473 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: ability to add/append data to csv files GENC-473

- server/build.gradle.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref seth-genc-543 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref seth-genc-543 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: Fix issue with test not trigger assemble itself GENC-543

- client-tmp/angular/package.json
[FUI-1967](https://genesisglobal.atlassian.net/browse/FUI-1967)
- adds missing package to package.json in angular
client-tmp/angular/package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/fix-angular-packages --no-npm --framework Angular
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/fix-angular-packages --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ …
```
> chore: fix package.json angular

- .genx/templates/web-components/form.hbs
- Change viewRight to updateRight in form component
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/fix-form-right --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/fix-form-right --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> fix: correct updateRight for form component GENC-574

- client-tmp/angular/README.md
- client-tmp/angular/package.json
[FUI-2054](https://genesisglobal.atlassian.net/browse/FUI-2054)
- [Upgrades Angular to v18](https://blog.angular.dev/angular-v18-is-now-available-e79d5ac0affe)
- Done using https://angular.dev/update-guide?v=17.0-18.0&l=1\
- But basically, just `ng update @angular/core@18 @angular/cli@18`...
- and also `@angular-builders/custom-webpack` that was released a few days ago ([see this](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#migration-from-version-17-to-version-18))
Quick one, check the `package.json` version bumps.
📑 &nbsp; **How should this …
> feat: upgrade angular client to v18 - FUI-2054

- .genx/templates/angular/route.hbs
- .genx/templates/angular/route.template.hbs
- .genx/utils/formatRouteData.js
- .genx/utils/gridSerializers.js
- client-tmp/angular/package.json
- client-tmp/angular/src/app/app-routing.module.ts
- client-tmp/angular/src/app/app.config.ts
- client-tmp/angular/src/app/guards/auth.guard.ts
- client-tmp/angular/src/app/share/foundation-login.ts
- client-tmp/angular/src/app/utils/formatters.ts
- client-tmp/angular/src/app/utils/index.ts
[GENC-547](https://genesisglobal.atlassian.net/browse/GENC-547)
- adds helpers: ```getDateFormatter``` / ```getNumberFormatter``` and use them in page template
- move ```AUTH_PATH``` to config file
- lint files in ./.genx
- client-tmp/angular/src/app/utils/formatters.ts
- .genx/templates/angular/route.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/GENC-547 --no-npm --framework Angular
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x …
```
> fix: adding missing formatting helpers GENC-547

- client-tmp/angular/package.json
GENC-547
- As titled
package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/GENC-547 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/GENC-547 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> chore: launching browser in Angular dev mode automatically GENC-547

- server/gradle.properties
- server/gradle/wrapper/gradle-wrapper.properties
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ferreirar/fix-prop-location --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ferreirar/fix-prop-location --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> fix: compactProcessesStrategy in the correct place

- client-tmp/angular/src/assets/initSSO.js
- client-tmp/angular/src/index.html
[FUI-2069](https://genesisglobal.atlassian.net/browse/FUI-2069)
- sso in angular
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/FUI-2069-sso-angular --no-npm
```
```
rm -rf blankappseedtest && npx -y npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/FUI-2069-sso-angular --framework Angular --enableSSO
```
> feat: sso in angular FUI-2069

- .genx/templates/angular/chart.hbs
- .genx/templates/angular/component/component.column.defs.hbs
- .genx/templates/angular/component/component.create.form.hbs
- .genx/templates/angular/component/component.gridOptions.hbs
- .genx/templates/angular/component/component.hbs
- .genx/templates/angular/component/component.index.hbs
- .genx/templates/angular/component/component.styles.hbs
- .genx/templates/angular/component/component.template.hbs
- .genx/templates/angular/component/component.update.form.hbs
- .genx/templates/angular/entityManager.hbs
- .genx/templates/angular/form.hbs
- .genx/templates/angular/grid.hbs
- .genx/templates/angular/gridLayout.hbs
- .genx/templates/angular/horizontalLayout.hbs
- .genx/templates/angular/route.hbs
- .genx/utils/generateRoute.js
- .genx/utils/generateTile.js
- .genx/utils/isString.js
- .genx/utils/validateFrameworkAlias.js
[FUI-2099](https://genesisglobal.atlassian.net/browse/FUI-2099)
- Implement the generated UI code structure proposal
- unrelated to the task: validation whether the --framework argument is a string
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/FUI-2099 --framework Angular --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/FUI-2099 --framework Angular  --no-npm -x --routes …
```
> feat: Implement the generated UI code structure proposal (angular)

- .genx/templates/react/grid.hbs
- .github/CODEOWNERS
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --framework React --ref ms/fix-react-grid-template --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My Positions","updateEvent":"EVENT_COUNTERPARTY_MODIFY","deleteEvent":"EVENT_COUNTERPARTY_DELETE","createEvent":"EVENT_COUNTERPARTY_INSERT", …
```
> fix: react grid template

- client-tmp/angular/package.json
- client-tmp/angular/src/declaration.d.ts
- adds missing dependencies and typing (pbc support for angular)
- client-tmp/angular/package.json
```
rm -rf blankappseedtest && \
mkdir -p blankappseedtest/seeds && cd blankappseedtest/seeds && \
git clone https://github.com/genesislcap/platform-auth.git --depth 1 && \
cp platform-auth/genx/.genx/versions.json.template platform-auth/genx/.genx/versions.json && \
sed -i '' -e "s/@foundationVersion@/14.*/" platform-auth/genx/.genx/versions.json && \
sed -i '' -e "s/@genesisVersion@/8.*/" platform-auth/genx/.genx/versions.json && \
sed -i '' -e "s/@client.version@/1.0.4/" platform-auth/genx/.genx/versions.json && \
cd platform-auth/client && rm ./package-lock.json && \ …
```
> chore: fix pbc integration - angular

- .genx/templates/angular/chart.hbs
- .genx/templates/angular/component/component.hbs
- .genx/templates/angular/entityManager.hbs
- .genx/templates/angular/form.hbs
- .genx/templates/angular/grid.hbs
- .genx/templates/angular/route.hbs
- improves the display of the message that the user does not have the right to display the component (angular)
- .genx/templates/angular/component/component.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/fix-not-permitted-angular --no-npm --framework Angular --apiHost "ws://public-foundation.genesislab.global/gwf/" --routes '[ { "name": "Home", "permissions": { "viewRight": null }, "tiles": [ { "title": "Grid", "type": "grid-pro", "config": { "resourceName": "ALL_TRADES", "permissions": { "viewRight": …
```
> chore: fix ErrorMessageComponent imports - angular

- .github/CODEOWNERS
PSD-9
- As titled
Code owners file
N/A
> chore: updated code owners PSD-9

- client-tmp/web-components/build.gradle.kts
[PA-1349](https://genesisglobal.atlassian.net/browse/PA-1349)
- Refreshes the node plugin under `client`, removing the responsibility from gradle to download node (this is a pre-requirement).
- It also changes the build definition to be aligned with our PBCs. 
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ferreirar/PA-1349 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ferreirar/PA-1349 --no-npm …
```
> fix: removing node versions from client build (PA-1349)

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref jay-taylerson-patch-2 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref jay-taylerson-patch-2 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: sanitise db namespace to avoid breaking postgres PTC-0

- .genx/templates/react/component/component.column.defs.hbs
- .genx/templates/react/component/component.create.form.hbs
- .genx/templates/react/component/component.gridOptions.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/react/component/component.index.hbs
- .genx/templates/react/component/component.styles.hbs
- .genx/templates/react/component/component.update.form.hbs
- .genx/utils/generateRoute.js
- .genx/utils/generateTile.js
[FUI-2139](https://genesisglobal.atlassian.net/browse/FUI-2139)
- Implement the generated UI code structure proposal
- .genx/templates/react/component/*
- .genx/utils/generateTile.js
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/FUI-2139 --framework React --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/FUI-2139 --framework React  --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> feat: Implement the generated UI code structure proposal (react) - FUI-2139

- .genx/configure.js
PA-1361
- As titled
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/local-gen-id-patch --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/local-gen-id-patch --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My Positions","updateEvent":"EVENT_COUNTERPARTY_MODIFY","deleteEvent":"EVENT_COUNTERPARTY_DELE …
```
> fix: handling multiple hyphens when generating DB namespace PA-1361

- .github/workflows/release.yml
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/release-trigger --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/release-trigger --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: ability to trigger release job manually PTC-0

- .genx/templates/angular/route.hbs
- .genx/templates/react/chart.hbs
- .genx/templates/react/component/component.gridOptions.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/react/component/component.index.hbs
- .genx/templates/react/entityManager.hbs
- .genx/templates/react/form.hbs
- .genx/templates/react/grid.hbs
- .genx/templates/react/gridLayout.hbs
- .genx/templates/react/horizontalLayout.hbs
- .genx/templates/react/route.hbs
- .genx/utils/generateTile.js
- client-tmp/react/package.json
- client-tmp/react/src/App.tsx
- client-tmp/react/src/share/foundation-login.ts
- client-tmp/react/src/utils/fdc3.ts
- client-tmp/react/src/utils/history.ts
- client-tmp/react/src/utils/index.ts
[FUI-2136](https://genesisglobal.atlassian.net/browse/FUI-2136)
- Adds support for subscribing to FDC3 channels on ready
- Adds support for sending FDC3 messages on grid events
- Removes tails data from the route + fixes issues with gridLayout/horizontalLayout
- client-tmp/react/src/App.tsx
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/FUI-2136 --no-npm -x --framework React --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> chore: FDC3 support in react - FUI-2136

- .genx/templates/react/route.hbs
[FUI-2133](https://genesisglobal.atlassian.net/browse/FUI-2133)
- disables layout caching when in development in react
'.genx/template/react/route.hbs`
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref %YOUR-BRANCH-NAME% --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref %YOUR-BRANCH-NAME% --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", …
```
> chore: disabled layout caching when in development in react

- client-tmp/react/package.json
- Fixes commands in package.json from unit tests (example unit tests will be implemented in a separate task)
- client-tmp/react/package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/fix-npm-task --no-npm --framework React
```
try run commands:
```
"test": "genx test"
"test:coverage": "genx test --no-watch --coverage",
"test:unit:watch": "genx test --watch"
```
> fix: update unit test commands in package.json

- .genx/templates/angular/entityManager.hbs
- .genx/templates/react/entityManager.hbs
- .genx/templates/web-components/entityManager.hbs
GENC-762
- add entityLabel so toast popups tell us the type of entity added
Web components:
https://github.com/user-attachments/assets/ab692fd1-d8e1-4854-80ca-7943a5e9adec
Angular:
https://github.com/user-attachments/assets/f6abc06d-bd17-4169-87f1-e55af9453cb5
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-762 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-762 --no-npm -x --routes …
```
> feat: add entityLabel so toast popups tell us the type of entity added GENC-762

- .genx/templates/react/component/component.hbs
- .genx/templates/react/component/component.index.hbs
- .genx/templates/react/route.hbs
- .genx/utils/generateRoute.js
- .genx/utils/generateTile.js
- client-tmp/react/.babelrc
- client-tmp/react/jest.config.js
- client-tmp/react/jest.setup.js
- client-tmp/react/package.json
- client-tmp/react/src/App.tsx
- client-tmp/react/src/components/ErrorMessage/ErrorMessage.test.js
- client-tmp/react/src/pages/AuthPage/AuthPage.test.js
- client-tmp/react/src/pages/NotPermittedPage/NotPermittedPage.test.js
[FUI-2173](https://genesisglobal.atlassian.net/browse/FUI-2173)
- Adds example unit tests in Jest
- Standardizes file names for react (using pascalCase)
- tests: client-tmp/react/src/pages/AuthPage/AuthPage.test.js / client-tmp/react/src/pages/NotPermittedPage/NotPermittedPage.test.js
- .genx/utils/generateTile.js
npm commands:
```
"test": "jest",
"test:coverage": "jest --coverage",
"test:unit:watch": "jest --watchAll",
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/FUI-2173 …
```
> feat: add unit tests - FUI-2173

- .gitignore
- VSCode web zip files are generated under this folder for the user to download.
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ignore-project-zips --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ignore-project-zips --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": …
```
> fix: ignore project-zips folder CIDE-53

- README.md
[GENC-845](https://genesisglobal.atlassian.net/browse/GENC-845)
- restructures layout of  ReadMe 
- Add extra curling brace around `description` in order to avoid HTML escaping in handlebars which is what was causing the issue in create ReadMe
root ReadMe
- added a description flag with the following content inside : ' ':
```
> This is a blockquote.
> Want to write on a new line with space between?
>
> > And nested? No problem at all.
> >
> > > PS. you can **style** your text _as you want_.
```
```
rm -rf blankappseedtest && npx …
```
> fix: reformat ReadMe layout & allow markdown in description GENC-845

- .gitignore
- README.md
- server/build.gradle.kts
- server/gradle.properties
- server/settings.gradle.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref launcher-support --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref launcher-support --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: add genesis launcher

- .genx/configure.js
- .genx/prompts.js
- .genx/prompts/server.js
- .genx/static.js
- .genx/utils/deleteGradleWrappers.js
- .genx/utils/index.js
- settings.gradle.kts
GENC-824
- Adds a new `excludeGradleWrapper` CLI param
```
$ find . -name "*.jar"
./server/gradle/wrapper/gradle-wrapper.jar
./gradle/wrapper/gradle-wrapper.jar
```
```
$ find . -name "*.jar"
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/GENC-824 --no-npm --excludeGradleWrapper
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ac/GENC-824 --no-npm
```
> feat: allow excluding Gradle wrappers GENC-824

- client-tmp/react/package.json
- update the react to ```19.0.0-rc-ed966dac-20241007```
_- client-tmp/react/package.json_
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/update-react --no-npm --framework React
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/update-react --no-npm -x  --framework React --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: update react version

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
- .genx/utils/generateRoute.js
GENC-857
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/GENC-857 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager", "metadata": { "comment": "My insightful comment", "todo": "TODO: Fix all the bugs" }, "type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My Positions","updateEvent":"EVENT_COUNTERPARTY_MODIFY","deleteE …
```
> feat: adding support for comments/todos in generated UI files GENC-857

- client-tmp/react/src/share/foundation-login.ts
- Uses the path from the first link in the routes [] as the home (React)
- Sets the value of autoConnect to true for foundation-login
- client-tmp/react/src/share/foundation-login.ts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ak/fix-home-routing --no-npm --framework React
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/fix-home-routing --no-npm -x --framework React --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> fix: home page url - react

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
GENC-857
- Align todo handling with Kotlin codegen
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/GENC-857 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager", "metadata": { "comment": "My insightful comment", "todo": "Fix all the bugs" }, "type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, "resourceName":"ALL_POSITIONS","title":"My …
```
> fix: prefix todo comment GENC-857

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
GENC-853
- Combines to-do an comment into a single code comment block
Comment and todo (if both provided) should rendered the same mutli-line comment block
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/GENC-853 --no-npm -x --routes '[{"name":"Both","tiles":[{"metadata": { "comment": "Comment", "todo": "And a todo" }, "title":"Tile","type":"grid-pro","config":{"resourceName":"ALL_POSITIONS"}}]}, {"name":"Comment","tiles":[{"metadata": { "comment": …
```
> fix: todo and comment formatting (GENC-853)

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
GENC-853
- Backports https://github.com/genesiscommunitysuccess/blank-app-seed/pull/376 to prerelease branch
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ac/prerelease-GENC-853 --no-npm -x --routes '[{"name":"Both","tiles":[{"metadata": { "comment": "Comment", "todo": "And a todo" }, "title":"Tile","type":"grid-pro","config":{"resourceName":"ALL_POSITIONS"}}]}, {"name":"Comment","tiles":[{"metadata": { "comment": "Comment only" }, …
```
> fix: back-porting todo formatting fix to prerelease branch GENC-853

- server/build.gradle.kts
- server/gradle.properties
- server/settings.gradle.kts
launcher to start
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref rename-launcher --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref rename-launcher --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": …
```
> chore: rename launcher to start (#380)

- client-tmp/react/public/index.html
- client-tmp/react/src/guards/ProtectedGuard.tsx
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/GENC-892-base-path-support --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/GENC-892-base-path-support --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> feat: support base path in react app GENC-892

- .github/workflows/upgrade.yml
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref skawian-patch-1 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref skawian-patch-1 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: Update upgrade.yml

- .genx/templates/angular/gridLayout.hbs
- .genx/templates/react/gridLayout.hbs
- .genx/templates/web-components/gridLayout.hbs
GENC-910
```
export const OrdersTemplate = html<Orders>`
<rapid-layout auto-save-key="${() => persistLayout('Orders_1730981573853')}">
<rapid-layout-region type="horizontal">
<rapid-layout-region type="vertical">
<rapid-layout-item title="">
<></>
</rapid-layout-item>
<rapid-layout-item title="">
<></>
</rapid-layout-item>
</rapid-layout-region>
<rapid-layout-region type="vertical">
<rapid-layout-item title="">
<></>
</rapid-layout-item>
<rapid-layout-item title="">
<></>
</rapid-layout-item>
</rapid-layout-region>
</rapid-layout-region>
</rapid-layout>
`;
```
```
export const OrdersTemplate = …
```
> fix: references in grid layout template GENC-910

- client-tmp/react/public/index.html
(cherry picked from commit 04e6935f9f04b7e32e9847a8ef557e4f2032676c)
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/cherry-pick-react --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/cherry-pick-react --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ …
```
> fix: script name for react template (GENC-892) (#388)

- client-tmp/web-components/package.json
N/A
- web-components client wasn't following the same FDC3 rules from other clients.. fixed
- foundation-forms override for AJV dep is not necessary anymore 
Check the single file change.
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref bw/web-overrides-cleanup --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref bw/web-overrides-cleanup --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> chore: tweak overrides in web client package.json - FUI-0

- client-tmp/react/src/helpers/hasPermissionHelper.tsx
[FUI-2244](https://genesisglobal.atlassian.net/browse/FUI-2244)
- fixes a helper to prevent users from accessing views they don’t have permission to
- client-tmp/react/src/helpers/hasPermissionHelper.tsx
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ak/FUI-2244 --no-npm -x --framework React --routes '", "valueFormatter": { "type": "function", "name": "getNumberFormatter", "category": "formatter", "arguments": [ "0,0.00", null ] }, "meta": { "gridDisplay": { "mode": "visible", "type": …
```
> fix: react client - route level permissions - FUI-2244

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
- .genx/utils/formatRouteData.js
- .genx/utils/getTodosAndComments.js
[GENC-898](https://genesisglobal.atlassian.net/browse/GENC-898)
-  align UI ToDo code generation output with server code
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-898 --no-npm -x --routes '[{"name":"Both","tiles":[{"metadata": { "comment": "This pipeline reads from genesisDB and writes to Kafka. This is a very long comment that should be -------- This line is split \nsplit in two different lines\nsecond line. ---- This is a \\n ", "todo": …
```
> fix: align UI todo/comment code generation output with server code GENC-898

- README.md
- client-tmp/web-components/README.md
- client-tmp/web-components/src/pbc/README.md
- client-tmp/web-components/test/README.md
- server/README.md
- server/{{appName}}-app/src/test/kotlin/global/genesis/EventHandlerTest.kt
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref suarezc/GENC-938 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref suarezc/GENC-938 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: update URL links (GENC-938)

- server/gradle.properties
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref jay-taylerson-patch-3 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref jay-taylerson-patch-3 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: Upgrade Genesis Start version (GENC-0)

- server/gradle.properties
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref genesis-start-version --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref genesis-start-version --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: Upgrading genesisStart to latest version (GENC-0)

- server/build.gradle.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref pozoj/GSF-5489 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref pozoj/GSF-5489 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: changes to upgrade to Kotlin 2.1.0 (GSF-5489)

- package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref pre-releaseversion --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref pre-releaseversion --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: adjusting pre-release version

- .genx/templates/angular/component/component.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
- .genx/templates/web-components/component/component.template.hbs
- .genx/templates/web-components/entityManager.hbs
[GENC-956](https://genesisglobal.atlassian.net/browse/GENC-956)
- Custom events for entity manager
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-956 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-956 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": …
```
> feat: ability to add custom events in entity-manager GENC-956

- .genx/templates/web-components/component/component.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/GENC-956-v2 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-956-v2 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: add tooltip to customEvent GENC-956

- .genx/templates/web-components/component/component.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/patch-1 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/patch-1 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: customEvent tooltip update GENC-847

- client-tmp/web-components/src/layouts/default.ts
[PA-1578](https://genesisglobal.atlassian.net/browse/PA-1578)
- navigate to correct route when logout
1. Logout after logging in using username and password
2. Logout after logging in using refresh token
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/logout-route --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/logout-route --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> fix: navigate to correct route when logout PA-1578

- .idea/workspace.xml
- client-tmp/angular/src/app/share/foundation-login.ts
- client-tmp/react/package.json
- client-tmp/react/src/App.tsx
- client-tmp/react/src/config.ts
- client-tmp/react/src/guards/ProtectedGuard.tsx
- client-tmp/react/src/layouts/default/DefaultLayout.tsx
- client-tmp/react/src/pages/AuthPage/AuthPage.tsx
- client-tmp/react/src/pbc/container.tsx
- client-tmp/react/src/share/foundation-login.ts
- client-tmp/react/src/store/RoutesContext.tsx
- client-tmp/react/src/utils/history.ts
- client-tmp/react/src/utils/index.ts
- client-tmp/web-components/src/routes/config.ts
```
rm -rf test_seedreact_react_simple && npx -y @genesislcap/genx@latest init test_seedreact_react_simple -x --ref ms/react-router-fix --no-npm --no-shell --framework React  && cd test_seedreact_react_simple/client && npm run bootstrap && npm run dev
```
> fix: react and angular router fix

- client-tmp/react/package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/react-router-fix --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/react-router-fix --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: react conflicting dependency (FUI-0) 

- client-tmp/web-components/package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref skawian-patch-1 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref skawian-patch-1 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: webpack version change

- client-tmp/web-components/src/routes/config.ts
- server/settings.gradle.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref szymon-patch-1 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref szymon-patch-1 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: adding the deploy plugin instructions PSD-0

- client-tmp/angular/src/app/share/foundation-auth.ts
- client-tmp/angular/src/proxy.conf.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/angular-fixes --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/angular-fixes --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: proxy fixes for angular

- server/{{appName}}-app/src/main/genesis/data/PROFILE_USER.csv
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref reporting-profile --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref reporting-profile --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: Add new REPORTING profile to seed (RPT-0)

- CHANGELOG.md
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/backport-main --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/backport-main --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: backport main GENC-0

- gradle.properties
- server/gradle.properties
…
- Reduce Gradle max heap settings from 6g to 3g.
- Split Kotlin daemon to separate config and increase max heap from 2g to 3g. Also setup G1GC with string deduplication to save memory.
- This change introduces potential max heap savings of 2g
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref pozoj/tweak-heap --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init …
```
> fix: tweak unnecessarily big max heap settings for gradle daemon (GENC-0)

- .genx/package.json
- CHANGELOG.md
- package-lock.json
- package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref %YOUR-BRANCH-NAME% --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref %YOUR-BRANCH-NAME% --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: backport main PSD-0

- .genx/templates/react/component/component.events.config.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/react/entityManager.hbs
- .genx/templates/web-components/component/component.events.config.hbs
- .genx/templates/web-components/component/component.hbs
- .genx/templates/web-components/component/component.template.hbs
- .genx/templates/web-components/entityManager.hbs
- .genx/utils/formatRouteData.js
- .genx/utils/generateTile.js
- client-tmp/react/src/custom-elements.d.ts
- client-tmp/react/src/utils/customEvents.ts
- client-tmp/web-components/src/utils/customEvents.ts
GENC-1002
- Advanced custom events from create config
- Ability to map custom events to buttons or foundation-forms
GENERATED APP FOR SERVER: 
- build and start the server, and later run UI from commands bellow 
[equity-allocations (21).zip](https://github.com/user-attachments/files/20672341/equity-allocations.21.zip)
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-1002 --no-npm -x --routes …
```
> feat: advanced custom events (react/web-components) GENC-1002

- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/entityManager.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/patch-3 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/patch-3 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: show title in custom events modal GENC-0

- .genx/templates/react/component/component.hbs
- .genx/templates/web-components/component/component.hbs
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref ms/PA-1716 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref ms/PA-1716 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: remove field name for custom events PA-1716

- .genx/templates/react/component/component.events.config.hbs
- .genx/templates/react/component/component.hbs
- .genx/templates/react/entityManager.hbs
- .genx/templates/web-components/component/component.hbs
- .genx/templates/web-components/component/component.template.hbs
- .genx/templates/web-components/entityManager.hbs
- client-tmp/react/package.json
- client-tmp/react/src/custom-elements.d.ts
- client-tmp/react/src/share/genesis-components.ts
- client-tmp/react/src/utils/customEvents.ts
- client-tmp/web-components/src/components/components.ts
- client-tmp/web-components/src/utils/customEvents.ts
BUILD AND RUN SERVER FROM:
[equity-allocations (4).zip](https://github.com/user-attachments/files/21147355/equity-allocations.4.zip)
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/GENC-1162 --no-npm -x --routes '[{"name":"HOME","layoutType":null,"permissions":null,"tiles":[{"title":"Entity1","type":"entity-manager","config":{"resourceName":"TRADE","permissions":{"updateRight":"Enti …
```
> feat: use smart-form-modal GENC-1162

- server/build.gradle.kts
- server/settings.gradle.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref pk/add-test-plugin --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref pk/add-test-plugin --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> feat: add-test-plugin PTC-0

- server/gradle.properties
- server/settings.gradle.kts
- server/{{appName}}-app/build.gradle.kts
- server/{{appName}}-app/src/test/resources/1-payload/Test/P_R_Test.json
- server/{{appName}}-app/src/test/resources/1-payload/global/P_login.json
- server/{{appName}}-app/src/test/resources/1-payload/global/P_logout.json
- server/{{appName}}-app/src/test/resources/4-config/config.properties
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref IncludeBDDVersionAndRepositories --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref IncludeBDDVersionAndRepositories --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, …
```
> Tesst folders created and bdd version added

- bdd-tests/src/test/resources/4-config/config.properties
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref matteematt-patch-1 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref matteematt-patch-1 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: set default baseuri to allow local running bdd tests GENC-1171

- client-tmp/angular/package.json
- client-tmp/react/package.json
- client-tmp/web-components/package.json
Override @analytics/core to 0.12.17 
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/patch-fix --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/patch-fix --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: override analytics FUI-0

- client-tmp/angular/package.json
- client-tmp/react/package.json
- client-tmp/web-components/package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/backport-main --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/backport-main --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: backport main FUI-0

- client-tmp/web-components/src/main/main.styles.ts
N/A - Chrome 139 compatibility fix
- Adds CSS selector `foundation-auth:defined` to ensure the element is visible when defined
- Fixes compatibility issues with Chrome 139 where custom elements may not render properly
- Maintains backward compatibility with older browser versions
- Addresses visibility issues during the initial render cycle in Chrome 139
- `client-tmp/web-components/src/main/main.styles.ts` - Review the added CSS selector
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x …
```
> fix: Add foundation-auth:defined selector for Chrome 139 compatibility

- .genx/package.json
- CHANGELOG.md
- client-tmp/web-components/src/main/main.styles.ts
- package-lock.json
- package.json
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref sz/backport --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref sz/backport --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> fix: backport main to prerelease FUI-0

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref jay-taylerson-patch-3 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref jay-taylerson-patch-3 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: Update genesis-system-definition.kts GENC-0

- server/{{appName}}-app/src/main/genesis/cfg/genesis-system-definition.kts
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref jay-taylerson-patch-3 --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref jay-taylerson-patch-3 --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity manager","type":"entity-manager","config":{ "modalPosition": "centre", "sizeColumnsToFit": true, "enableSearchBar": true, …
```
> chore: Fix zerMq sysdef typo GENC-0

- client-tmp/web-components/src/index.federated.ts
remove this index-federated.ts file as it is related to module federation which is not used in any app. 
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest -x --ref gs/module-federation --no-npm
```
```
rm -rf blankappseedtest && npx -y @genesislcap/genx@latest init blankappseedtest --ref gs/module-federation --no-npm -x --routes '[{"name":"Home","tiles":[{"title":"Entity …
```
> fix: remove index-federated.ts file
